### ISSUE TITLE
Update the ingestion configs to support frames and ctf

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#1054]
## Tasks

The ingestion config must be updated to support new fields.

### frames
Add the following fields to frame metadata.

|   Name | Data type  | Nullable | Migration notes |
|---|---|---|---|
| dose_rate | float | false | Set this to a invalid stub that fails validation check if frames exist, else compute dose_rate from `tiltseries.total_flux` |
| is_gain_corrected | bool | true |  true if gain files exist else false |

#### Example
```
frames:
- metadata:
   dose_rate: 1.2
   is_gain_corrected: false
 sources:
 - source_glob:
     list_glob: '{run_name}/frames/*.eer'

```

### ctf

Add a new entity for ctf.

Add the following fields to ctf metadata.

|   Name | Data type  | Nullable | Migration notes |
|---|---|---|---|
| format | ENUM[“ctffind”, “None”] | false |  Default to "ctffind" |

The sources for this are similar to the rawtlt entity.

#### Example
```
ctf:
- metadata:
   format: ctffind
 sources:
 - source_multi_glob:
     list_globs:
     - chlamy_visual_proteomics/{run_name}/ctffind4/ctfphaseflip_ctffind4.txt
```

## What done Looks Like

- The config validation can support these fields

## Reference
- https://github.com/chanzuckerberg/cryoet-data-portal-backend/tree/main/schema/ingestion_config/v1.0.0
