### ISSUE TITLE
Expand tomogram processing enum

### ISSUE THREAD

**Issue by uermel** [chanzuckerberg/cryoet-data-portal#1710]
In order to properly label special versions of tomograms used for training denoising networks in the short term it would be great if we could expand the `Tomogram.processing` enum. These tomograms are created using information from just half the frames in each movie stack and usually used as input to Noise2Noise networks.

These are the two values I'd like to see added: 
```
      filtered_even:
        text: filtered_even
        description: Tomogram was filtered, created from even frames
      filtered_odd:
        text: filtered_odd
        description: Tomogram was filtered, created from odd frames
```
